CREATE TABLE [dbo].[Clients] (
    [CAId]                                 INT             IDENTITY (1, 1) NOT NULL,
    [DisplayClientId]                      NVARCHAR (30)   NOT NULL,
    [CompanyName]                          NVARCHAR (200)  NOT NULL,
    [RegistrationDate]                     DATETIME        NULL,
    [Alias]                                NVARCHAR (10)   NULL,
    [Image]                                NVARCHAR (255)  NULL,
    [PAN]                                  NVARCHAR (20)   NULL,
    [TAN]                                  NVARCHAR (20)   NULL,
    [Email1]                               NVARCHAR (100)  NULL,
    [Email2]                               NVARCHAR (100)  NULL,
    [Website]                              NVARCHAR (100)  NULL,
    [IsActive]                             BIT             NOT NULL,
    [IsDeleted]                            BIT             NOT NULL,
    [Status]                               NVARCHAR (15)   NOT NULL,
    [AllowEdit]                            BIT             NOT NULL,
    [APMCLicenseNo]                        NVARCHAR (255)  NULL,
    [NoOfPartners]                         INT             NOT NULL,
    [TDSOnSubscriptionPayment]             DECIMAL (19, 5) NOT NULL,
    [AdditionalInfoForSubscriptionPayment] NVARCHAR (255)  NULL,
    [APMCLicenseValidUpTo]                 DATETIME        NULL,
    [CreatedBy]                            BIGINT          NOT NULL,
    [CreatedDate]                          DATETIME        DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]                           BIGINT          NOT NULL,
    [ModifiedDate]                         DATETIME        DEFAULT (getdate()) NOT NULL,
    [AccountManagerId]                     BIGINT          NOT NULL,
    [AddressId]                            BIGINT          NULL,
    [APMCId]                               INT             NULL,
    [BusinessConstitutionId]               INT             NULL,
    [ClientSubscriptionId]                 INT             NULL,
    [ClientPhoneChargesId]                 INT             NULL,
    [CAPrimaryContactPersonId]             INT             NULL,
    PRIMARY KEY CLUSTERED ([CAId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

