CREATE TABLE [dbo].[ClientPartnerDetails] (
    [PartnerId]               INT             IDENTITY (1, 1) NOT NULL,
    [Title]                   NVARCHAR (10)   NULL,
    [PartnerName]             NVARCHAR (255)  NULL,
    [Gender]                  NVARCHAR (5)    NULL,
    [DateOfBirth]             DATETIME        DEFAULT (getdate()) NULL,
    [PAN]                     NVARCHAR (20)   NULL,
    [UID]                     NVARCHAR (20)   NULL,
    [Image]                   NVARCHAR (255)  NULL,
    [Email1]                  NVARCHAR (100)  NULL,
    [Email2]                  NVARCHAR (100)  NULL,
    [JoiningDate]             DATETIME        DEFAULT (getdate()) NULL,
    [RelievingDate]           DATETIME        DEFAULT (getdate()) NULL,
    [PartnerDisplayId]        NVARCHAR (30)   NULL,
    [MaritialStatus]          NVARCHAR (10)   NULL,
    [PassportNo]              NVARCHAR (30)   NULL,
    [Place]                   NVARCHAR (100)  NULL,
    [IssuedOn]                DATETIME        DEFAULT (getdate()) NULL,
    [ValidUpTo]               DATETIME        DEFAULT (getdate()) NULL,
    [PartnerType]             NVARCHAR (10)   NULL,
    [CapitalRatio]            DECIMAL (19, 5) NOT NULL,
    [ProfitRatio]             DECIMAL (19, 5) NOT NULL,
    [SalaryRatio]             DECIMAL (19, 5) NOT NULL,
    [LossRatio]               DECIMAL (19, 5) NOT NULL,
    [OpeningBalance]          DECIMAL (19, 5) NOT NULL,
    [BalanceType]             NVARCHAR (5)    NULL,
    [AsOndate]                DATETIME        DEFAULT (getdate()) NULL,
    [IsActive]                BIT             NOT NULL,
    [CreatedBy]               BIGINT          NOT NULL,
    [CreatedDate]             DATETIME        DEFAULT (getdate()) NOT NULL,
    [ModifiedBy]              BIGINT          NOT NULL,
    [ModifiedDate]            DATETIME        DEFAULT (getdate()) NOT NULL,
    [AddressId]               BIGINT          NULL,
    [DesignationId]           INT             NULL,
    [ClientPartnerGuardianId] INT             NULL,
    [ClientPartnerNomineeId]  INT             NULL,
    PRIMARY KEY CLUSTERED ([PartnerId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

