CREATE TABLE [dbo].[ParentChildMenus] (
    [MenuId]       BIGINT NOT NULL,
    [MenuOrder]    INT    NOT NULL,
    [ParentMenuId] BIGINT NULL,
    [ChildMenuId]  BIGINT NULL,
    PRIMARY KEY CLUSTERED ([MenuId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

