CREATE TABLE [dbo].[States] (
    [StateId]    INT           IDENTITY (1, 1) NOT NULL,
    [RegionType] NVARCHAR (50) NOT NULL,
    [RegionName] NVARCHAR (50) NOT NULL,
    [CountryId]  INT           NULL,
    PRIMARY KEY CLUSTERED ([StateId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

