CREATE TABLE [dbo].[Users] (
    [UserId]                           BIGINT         IDENTITY (1, 1) NOT NULL,
    [Username]                         NVARCHAR (255) NOT NULL,
    [Title]                            NVARCHAR (5)   NOT NULL,
    [Name]                             NVARCHAR (255) NOT NULL,
    [Email]                            NVARCHAR (255) NOT NULL,
    [MobileNo]                         NVARCHAR (255) NOT NULL,
    [Password]                         NVARCHAR (255) NOT NULL,
    [MothersMaidenName]                NVARCHAR (255) NOT NULL,
    [CAId]                             INT            NULL,
    [CountryCode]                      NVARCHAR (255) NOT NULL,
    [CreatedBy]                        BIGINT         NOT NULL,
    [CreatedDate]                      DATETIME       DEFAULT (getdate()) NOT NULL,
    [DateOfBirth]                      DATETIME       DEFAULT (getdate()) NOT NULL,
    [FailedPasswordAttemptCount]       INT            NULL,
    [FailedPasswordAttemptWindowStart] DATETIME       DEFAULT (getdate()) NULL,
    [IsActive]                         BIT            NOT NULL,
    [IsLockedOut]                      BIT            NOT NULL,
    [IsOnLine]                         BIT            NOT NULL,
    [LastActivityDate]                 DATETIME       DEFAULT (getdate()) NULL,
    [LastLockedOutDate]                DATETIME       DEFAULT (getdate()) NULL,
    [LastLoginDate]                    DATETIME       DEFAULT (getdate()) NULL,
    [LastPasswordChangedDate]          DATETIME       DEFAULT (getdate()) NULL,
    [ModifiedBy]                       BIGINT         NULL,
    [ModifiedDate]                     DATETIME       DEFAULT (getdate()) NULL,
    [LastPassword]                     NVARCHAR (255) NULL,
    [SecondLastPassword]               NVARCHAR (255) NULL,
    [SecondLastPasswordChangedDate]    DATETIME       DEFAULT (getdate()) NULL,
    [IsDeleted]                        BIT            NOT NULL,
    [AllowEdit]                        BIT            NOT NULL,
    [AllowDelete]                      BIT            NOT NULL,
    [Image]                            NVARCHAR (255) NULL,
    [UserType]                         NVARCHAR (15)  NULL,
    [DesignationId]                    INT            NULL,
    [UserProfileId]                    BIGINT         NULL,
    PRIMARY KEY CLUSTERED ([UserId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF)
);

