//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cams.UnitTests.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorAndValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorAndValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cams.UnitTests.ResourceFiles.ErrorAndValidationMessages", typeof(ErrorAndValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must enter date of birth.
        /// </summary>
        internal static string BRDateOfBirth {
            get {
                return ResourceManager.GetString("BRDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter designation name.
        /// </summary>
        internal static string BRDesignationName {
            get {
                return ResourceManager.GetString("BRDesignationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation name already exist.
        /// </summary>
        internal static string BRDesignationUnique {
            get {
                return ResourceManager.GetString("BRDesignationUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must have a valid email address.
        /// </summary>
        internal static string BREmail {
            get {
                return ResourceManager.GetString("BREmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must have a valid mobile number.
        /// </summary>
        internal static string BRMobileNo {
            get {
                return ResourceManager.GetString("BRMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must have a valid mothers maiden name.
        /// </summary>
        internal static string BRMothersMaidenName {
            get {
                return ResourceManager.GetString("BRMothersMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must have a valid name.
        /// </summary>
        internal static string BRName {
            get {
                return ResourceManager.GetString("BRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must enter password.
        /// </summary>
        internal static string BRPassword {
            get {
                return ResourceManager.GetString("BRPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter relationship name.
        /// </summary>
        internal static string BRRelationshipName {
            get {
                return ResourceManager.GetString("BRRelationshipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship name already exist.
        /// </summary>
        internal static string BRRelationshipUnique {
            get {
                return ResourceManager.GetString("BRRelationshipUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid usergroup.
        /// </summary>
        internal static string BRUserGroupNameDisplay {
            get {
                return ResourceManager.GetString("BRUserGroupNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup must have a name.
        /// </summary>
        internal static string BRUserGroupNameRequired {
            get {
                return ResourceManager.GetString("BRUserGroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserGroup already exist.
        /// </summary>
        internal static string BRUserGroupNameUnique {
            get {
                return ResourceManager.GetString("BRUserGroupNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must enter a username.
        /// </summary>
        internal static string BRUserName {
            get {
                return ResourceManager.GetString("BRUserName", resourceCulture);
            }
        }
    }
}
