ALTER TABLE [dbo].[UserContacts]
    ADD CONSTRAINT [FK216270F817810183] FOREIGN KEY ([ContactDetailsId]) REFERENCES [dbo].[ContactDetails] ([ContactDetailsId]) ON DELETE NO ACTION ON UPDATE NO ACTION;

