ALTER TABLE [dbo].[EmailAttachments]
    ADD CONSTRAINT [FKD3D773844291588] FOREIGN KEY ([EmailMessageId]) REFERENCES [dbo].[EmailMessages] ([EmailMessageId]) ON DELETE NO ACTION ON UPDATE NO ACTION;

