-- =============================================
-- Script Template
-- =============================================
update UserProfiles set AddressId=null
update UsersEmergencyContactPerson set AddressId=null
delete from Addresses
delete from CityVillages
delete from Districts
delete from States

INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Andhra Pradesh',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Arunachal Pradesh',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Assam',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Bihar',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Chhattisgarh',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Goa',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Gujarat',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Haryana',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Himachal Pradesh',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Jammu and Kashmir',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Jharkhand',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Karnataka',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Kerala',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Madhya Pradesh',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Maharashtra',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Manipur',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Meghalaya',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Mizoram',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Nagaland',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Orissa',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Punjab',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Rajasthan',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Sikkim',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Tamil Nadu',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Tripura',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Uttar Pradesh',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','Uttarakhand',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('State','West Bengal',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('Union Territory','Andaman and Nicobar',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('Union Territory','Chandigarh',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('Union Territory','Dadra and Nagar Haveli',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('Union Territory','Daman and Diu',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('Union Territory','Lakshadweep',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('Union Territory','Delhi',1)
INSERT INTO [CAMS].[dbo].[States]([RegionType],[RegionName],[CountryId]) VALUES ('Union Territory','Pondicherry',1)

GO

Insert into Districts(DistrictName,StateId) values('Nellore', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Cuddapah', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Karim Nagar', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Kurnool', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('West Godavari', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Srikakulam', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Anantpur', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Adilabad', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Chittor', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('east Godavari', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Guntur', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Hyderabad Urban', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Khammam', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Krishna', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Mehboobnagar', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Medak', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Nalgonda', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Nizamabad', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Prakasam', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Ranga Reddy', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Vishakapatnam', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Vizianagaram', (select stateid from States where RegionName='Andhra Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Warangal', (select stateid from States where RegionName='Andhra Pradesh'))				
				
				
Insert into Districts(DistrictName,StateId) values('Karimganj', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Darrang', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Dibrugarh', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Morigaon', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Tinsukia', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Bongaigaon', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Nalbari', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Kokrajhar', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Kamrup', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Karbi-Anglong', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Nagaon', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('N.C.Hills', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Dhemaji', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Hailakandi', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Lakhimpur', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Sonitpur', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Dhubri', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Goalpara', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Barpeta', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Golaghat', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Jorhat', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Sibsagar', (select stateid from States where RegionName='Assam'))				
Insert into Districts(DistrictName,StateId) values('Cachar', (select stateid from States where RegionName='Assam'))				
				
				
Insert into Districts(DistrictName,StateId) values('Diban Valley( Anini Valley)', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('East Kameng Seppa', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Itanagar', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('East Siang(Passighat)', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Lohit(Tezu)', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Lower Subansiri(Ziro)', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Khonsa', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Roin', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Tawang', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Changalang', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Dibang Valley', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Daporijo', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Bomdila', (select stateid from States where RegionName='Arunachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Alog( West Siang )', (select stateid from States where RegionName='Arunachal Pradesh'))				
				
				
Insert into Districts(DistrictName,StateId) values('Muzaffarpur', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Jehanabad', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Gaya', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Patna', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Saran( Chapra )', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Darbhanga', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Saharsa', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Purnea', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Bhagalpur', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Munger', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Aurangabad', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Bhojpur(Arah)', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Begusarai', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('East Champaran', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Gopalganj', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Jamui', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Katihar', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Khagaria', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Madhepura', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Madhubani', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Nalanda', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Nawada', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Rohtas(Sasaram)', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Samastipur', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Sitamarhi', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Siwan', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Vaishali(Hajipur)', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('West Champaran', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Kishanganj', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Araria', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Bhabua', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Banka', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Buxar', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Supaul', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Sekhpura', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Seohar', (select stateid from States where RegionName='Bihar'))				
Insert into Districts(DistrictName,StateId) values('Lakhisarai', (select stateid from States where RegionName='Bihar'))				
				
				
Insert into Districts(DistrictName,StateId) values('Panchmahals', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Vadodara', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Amrela', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Kheda', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Ahmedabad', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Valsad', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Junagadh', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Mehsana', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Banaskantha', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Gandhinagar', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Bharuch', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Dangs', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Jamnagar', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Rajkot', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Surat', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Sabarkantha', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Kutch', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Bhavnagar', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Surendranagar', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Navsari', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Anand', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Narmada', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Patan', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Porbander', (select stateid from States where RegionName='Gujarat'))				
Insert into Districts(DistrictName,StateId) values('Dahod', (select stateid from States where RegionName='Gujarat'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Gurgaon', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Rohtak', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Ambala', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Bhiwani', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Faridabad', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Hissar', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Jind', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Kaithal', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Karnal', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Kurukshetra', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Mahendragarh', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Panchkula', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Panipat', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Sonipat', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Yamunanagar', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Sirsa', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Rewari', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Jhanjhar', (select stateid from States where RegionName='Haryana'))				
Insert into Districts(DistrictName,StateId) values('Fatehabad', (select stateid from States where RegionName='Haryana'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Sirmour', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Hamirpur', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Kullu', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Solan', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Mandi', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Chamba', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Bilaspur', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Kangra', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Kinnaur', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Lahaul-Spiti', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Shimla', (select stateid from States where RegionName='Himachal Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Una', (select stateid from States where RegionName='Himachal Pradesh'))				
				
				
Insert into Districts(DistrictName,StateId) values('Kathua', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Badgan', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Poonch', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Rajauri', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Baramula', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Doda', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Udhampur', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Jammu', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Kupwara', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Pulwama', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Anantnag', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Srinagar', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Leh', (select stateid from States where RegionName='Jammu and Kashmir'))				
Insert into Districts(DistrictName,StateId) values('Kargil', (select stateid from States where RegionName='Jammu and Kashmir'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Mysore', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Gulberga', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Chitradurga', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Kolar', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Bijapur', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Dakshina Kannada', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Raichur', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Bellary', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Belgaum', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Hassan', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Dharwad', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Bangalore Rural', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Shimoga', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Mandya', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Chickmagalur', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Bangalore Urban', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Madikeri', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Tumkur', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Bidar', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Karwar', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Udupi', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Davanagare', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Chamrajnagar', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Koppal', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Haveri', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Gadak', (select stateid from States where RegionName='Karnataka'))				
Insert into Districts(DistrictName,StateId) values('Yadgir', (select stateid from States where RegionName='Karnataka'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Kozhikode', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Kasaragod', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Idukki', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Ernakulam', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Cannanore', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Mallapuram', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Palghat', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Pathanamthitta', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Quilon', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Trichur', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Wayanad', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Trivandrum', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Kottayam', (select stateid from States where RegionName='Kerala'))				
Insert into Districts(DistrictName,StateId) values('Alapuzzha', (select stateid from States where RegionName='Kerala'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Sindi', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Vidisha', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Jabalpur', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Bhopal', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Hoshangabad', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Indore', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Rewa', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Satna', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Shahdol', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Chhindwara', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Ratlam', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Balaghat', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Betul', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Bhind', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Mandla', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Chhattarpur', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Damoh', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Datia', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Dewas', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Dhar', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Guna', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Gwalior', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Jhabua', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Sehore', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Mandsaur', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Narsinghpur', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Panna', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Raisen', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Rajgarh', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Sagar', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Seoni', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Morena', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Shivpuri', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Shajapur', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Tikamgarh', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Ujjain', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Khandwa', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Khargone', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Dindori', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Umaria', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Badwani', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Sheopur', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Katni', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Neemuch', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Harda', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Anooppur', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Burhanpur', (select stateid from States where RegionName='Madhya Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Ashoknagar', (select stateid from States where RegionName='Madhya Pradesh'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Aurangabad', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Bandra(Mumbai Suburban district)', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Nagpur', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Pune', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Akola', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Chandrapur', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Jalgaon', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Parbhani', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Sholapur', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Thane', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Latur', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Mumbai-City', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Buldhana', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Dhule', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Kolhpur', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Nanded', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Raigad', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Amravati', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Nashik', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Wardha', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Ahmednagar', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Beed', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Bhandara', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Gadchiroli', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Jalna', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Osmanabad', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Ratnagiri', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Sangli', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Satara', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Sindudurg', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Yavatmal', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Nandurbar', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Washim', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Gondia', (select stateid from States where RegionName='Maharashtra'))				
Insert into Districts(DistrictName,StateId) values('Hingoli', (select stateid from States where RegionName='Maharashtra'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Imphal East', (select stateid from States where RegionName='Manipur'))				
Insert into Districts(DistrictName,StateId) values('Imphal West', (select stateid from States where RegionName='Manipur'))				
Insert into Districts(DistrictName,StateId) values('Thoubal', (select stateid from States where RegionName='Manipur'))				
Insert into Districts(DistrictName,StateId) values('Bishnupur', (select stateid from States where RegionName='Manipur'))				
Insert into Districts(DistrictName,StateId) values('Chandel', (select stateid from States where RegionName='Manipur'))				
Insert into Districts(DistrictName,StateId) values('Churachandpur', (select stateid from States where RegionName='Manipur'))				
Insert into Districts(DistrictName,StateId) values('Senapati', (select stateid from States where RegionName='Manipur'))				
Insert into Districts(DistrictName,StateId) values('Ukhrul', (select stateid from States where RegionName='Manipur'))				
Insert into Districts(DistrictName,StateId) values('Tamenglong', (select stateid from States where RegionName='Manipur'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Ri-Bhoi District', (select stateid from States where RegionName='Meghalaya'))				
Insert into Districts(DistrictName,StateId) values('South Garo Hills', (select stateid from States where RegionName='Meghalaya'))				
Insert into Districts(DistrictName,StateId) values('East Khasi Hill', (select stateid from States where RegionName='Meghalaya'))				
Insert into Districts(DistrictName,StateId) values('East Garo Hill', (select stateid from States where RegionName='Meghalaya'))				
Insert into Districts(DistrictName,StateId) values('West Garo Hill', (select stateid from States where RegionName='Meghalaya'))				
Insert into Districts(DistrictName,StateId) values('Jaintia Hill', (select stateid from States where RegionName='Meghalaya'))				
Insert into Districts(DistrictName,StateId) values('West Khasi Hill', (select stateid from States where RegionName='Meghalaya'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Luglei District', (select stateid from States where RegionName='Mizoram'))				
Insert into Districts(DistrictName,StateId) values('Chimtipui District', (select stateid from States where RegionName='Mizoram'))				
Insert into Districts(DistrictName,StateId) values('Aizawal', (select stateid from States where RegionName='Mizoram'))				
Insert into Districts(DistrictName,StateId) values('Champhai', (select stateid from States where RegionName='Mizoram'))				
Insert into Districts(DistrictName,StateId) values('Mamit', (select stateid from States where RegionName='Mizoram'))				
Insert into Districts(DistrictName,StateId) values('Kolasib', (select stateid from States where RegionName='Mizoram'))				
Insert into Districts(DistrictName,StateId) values('Serchhip', (select stateid from States where RegionName='Mizoram'))				
Insert into Districts(DistrictName,StateId) values('Lawngtlai', (select stateid from States where RegionName='Mizoram'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Wokha', (select stateid from States where RegionName='Nagaland'))				
Insert into Districts(DistrictName,StateId) values('Phek', (select stateid from States where RegionName='Nagaland'))				
Insert into Districts(DistrictName,StateId) values('Tuensang', (select stateid from States where RegionName='Nagaland'))				
Insert into Districts(DistrictName,StateId) values('Mon', (select stateid from States where RegionName='Nagaland'))				
Insert into Districts(DistrictName,StateId) values('Kohima', (select stateid from States where RegionName='Nagaland'))				
Insert into Districts(DistrictName,StateId) values('Zunheboto', (select stateid from States where RegionName='Nagaland'))				
Insert into Districts(DistrictName,StateId) values('Mokokchung', (select stateid from States where RegionName='Nagaland'))				
Insert into Districts(DistrictName,StateId) values('Dimapur', (select stateid from States where RegionName='Nagaland'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Khurda', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Navaragpur', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Navapada', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Gajapati', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Boudh', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Bhadrak', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Ganjam', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Dhenkanal', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Angul', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Puri', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Cuttak', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Sambalpur', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Kalhandi', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Koraput', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Phulbani', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Balangir', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Bargah', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Deogarh', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Jagatsinghpur', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Jajpur', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Jharsuguda', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Kendrapara', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Malkangiri', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Nayagarh', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Rayagada', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Sonepur', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Balasore', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Mayurbhanj', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Keonjhar', (select stateid from States where RegionName='Orissa'))				
Insert into Districts(DistrictName,StateId) values('Sundergarh', (select stateid from States where RegionName='Orissa'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Sangrur', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Jalandhar', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Ludhiana', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Bhatinda', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Kapurthala', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Patiala', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Amritsar', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Ferozepur', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Fatehgarh Saheb', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Ropar', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Gurdaspur', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Hosiarpur', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Faridkot', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Mansa', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Moga', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Muktsar', (select stateid from States where RegionName='Punjab'))				
Insert into Districts(DistrictName,StateId) values('Navansahar', (select stateid from States where RegionName='Punjab'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Jaipur', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Barmer', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Dungarpur', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Jodhpur', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Kota', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Udaipur', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Bikaner', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Dausa', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Bundi', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Sikar', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Tonk', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Jaisalmer', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Nagaur', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Rajsamand', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Banswara', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Bhilwara', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Ajmer', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Alwar', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Bharatpur', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Chittorgarh', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Churu', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Dholpur', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Ganganagar', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Jalor', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Jhalawar', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Jhunjhunu', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Pali', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Sawai Madhopur', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Sirohi', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Baran', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Hanumangarh', (select stateid from States where RegionName='Rajasthan'))				
Insert into Districts(DistrictName,StateId) values('Karauli', (select stateid from States where RegionName='Rajasthan'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('East', (select stateid from States where RegionName='Sikkim'))				
Insert into Districts(DistrictName,StateId) values('South', (select stateid from States where RegionName='Sikkim'))				
Insert into Districts(DistrictName,StateId) values('West', (select stateid from States where RegionName='Sikkim'))				
Insert into Districts(DistrictName,StateId) values('North', (select stateid from States where RegionName='Sikkim'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Chennai', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Coimbotore', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Cuddalorei', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Dharmapuri', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Dindigul', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Erode', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Kancheepuram', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Kanniyakumari (HQ : Nagercoil)', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Karur', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Madurai', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Nagapattinam', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Namakkal', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Nilgiris (HQ: Udhagamandalam)', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Perambalur', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Pudukkottai', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Ramanathapuram', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Salem', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Sivaganga', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Thanjavur', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Theni', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Thoothkudi', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Tiruchiorappalli', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Tirunelveli', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Tiruvallur', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Tiruvannamalai', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Tiruvarur', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Vellore', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Villupuram', (select stateid from States where RegionName='Tamil Nadu'))				
Insert into Districts(DistrictName,StateId) values('Virudhunagar', (select stateid from States where RegionName='Tamil Nadu'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('North District', (select stateid from States where RegionName='Tripura'))				
Insert into Districts(DistrictName,StateId) values('South District', (select stateid from States where RegionName='Tripura'))				
Insert into Districts(DistrictName,StateId) values('West District', (select stateid from States where RegionName='Tripura'))				
Insert into Districts(DistrictName,StateId) values('Dhalai District', (select stateid from States where RegionName='Tripura'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Allahabad', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Aligarh', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Bareilly', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Gonda', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Hardoi', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Kanpur Dehat', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Ghaziabad', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Unnav', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Varanasi', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Faizabad', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Gorakpur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Jhansi', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Lucknow', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Agra', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Meerut', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Moradabad', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Barabanki', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Mainpuri', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Etawah', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Gazipur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Etah', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Muzaffar Nagar', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Saharanpur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Bulandshehar', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Mathura', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Firozabad', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Budaun', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Shahjahanpur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Pilibhit', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Bijnor', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Rampur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Kanpur(Nagar)', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Farrukhabad', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Fatehpur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Pratapgarh', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Jalaun', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Hamirpur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Lalitpur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Mirzapur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Basti', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Deoria', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Raebareili', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Sitapur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Banda', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Lakhimpur-Khedi', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Bahraich', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Sultanpur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Mau', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Azamgarh', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Jaunpur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Balia', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Bhadoi', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Padrauna', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Maharajganj', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Siddharth Nagar', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Sunbhadra', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Mahoba', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Ambedkarnagar', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Gautam Bodda Nagar', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Maha Maya Nagar', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('jyotiba Phoole Nagar', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Kaushambi', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Shooji Maharaj', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Chandauli', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Balrampur', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Shravati', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Bagpat', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Kanooj', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Oraiyya', (select stateid from States where RegionName='Uttar Pradesh'))				
Insert into Districts(DistrictName,StateId) values('Sant Kabir Nagar', (select stateid from States where RegionName='Uttar Pradesh'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Howrah', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Darjeeling', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Medinipur', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Murshidabad', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Coochbehar', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Malda', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Birbhum', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('North 24 Parganas', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('South 24 Parganas', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Bankura', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Bardhaman', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Jalpaiguri', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Hooghly', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Nadia', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Dakshin Dinajpur', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Purulia', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Uttar Dinajpur', (select stateid from States where RegionName='West Bengal'))				
Insert into Districts(DistrictName,StateId) values('Siliguri', (select stateid from States where RegionName='West Bengal'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Central Delhi', (select stateid from States where RegionName='Delhi'))				
Insert into Districts(DistrictName,StateId) values('North Delhi', (select stateid from States where RegionName='Delhi'))				
Insert into Districts(DistrictName,StateId) values('South Delhi', (select stateid from States where RegionName='Delhi'))				
Insert into Districts(DistrictName,StateId) values('East Delhi', (select stateid from States where RegionName='Delhi'))				
Insert into Districts(DistrictName,StateId) values('North East Delhi', (select stateid from States where RegionName='Delhi'))				
Insert into Districts(DistrictName,StateId) values('South West Delhi', (select stateid from States where RegionName='Delhi'))				
Insert into Districts(DistrictName,StateId) values('New Delhi', (select stateid from States where RegionName='Delhi'))				
Insert into Districts(DistrictName,StateId) values('North West Delhi', (select stateid from States where RegionName='Delhi'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('North Goa', (select stateid from States where RegionName='Goa'))				
Insert into Districts(DistrictName,StateId) values('South Goa', (select stateid from States where RegionName='Goa'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Karikal', (select stateid from States where RegionName='Pondicherry'))				
Insert into Districts(DistrictName,StateId) values('Mahe', (select stateid from States where RegionName='Pondicherry'))				
Insert into Districts(DistrictName,StateId) values('Yaman', (select stateid from States where RegionName='Pondicherry'))				
Insert into Districts(DistrictName,StateId) values('Pondicherry', (select stateid from States where RegionName='Pondicherry'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Lakshdweep', (select stateid from States where RegionName='Lakshadweep'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Dama', (select stateid from States where RegionName='Daman and Diu'))				
Insert into Districts(DistrictName,StateId) values('Diu', (select stateid from States where RegionName='Daman and Diu'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Dadra', (select stateid from States where RegionName='Dadra and Nagar Haveli'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Chandigarh', (select stateid from States where RegionName='Chandigarh'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Andaman', (select stateid from States where RegionName='Andaman and Nicobar'))				
Insert into Districts(DistrictName,StateId) values('Nicobar', (select stateid from States where RegionName='Andaman and Nicobar'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Nainital', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Almora', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Pitoragarh', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Udhamsingh Nagar', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Bageshwar', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Champawat', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Garhwal(Pauri)', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Tehri-Garhwal', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Chamoli( Gopeshwar )', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Uttarkashi', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Dehradun', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Rudraprayag', (select stateid from States where RegionName='Uttarakhand'))				
Insert into Districts(DistrictName,StateId) values('Haridwar', (select stateid from States where RegionName='Uttarakhand'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Deoghar', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Dhanbad', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Giridih', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Godda', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Gumla', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Hazaribagh', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Lohardaga', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Palamu', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Ranchi', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Dumka', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Chaibasa(West Singhbhum)', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Jamshedpur(East Singhbhum)', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Bokaro', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Chatra', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Garhwa', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Koderma', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Pakur', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Sahebganj', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Simdega', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Latehar', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Saraikela', (select stateid from States where RegionName='Jharkhand'))				
Insert into Districts(DistrictName,StateId) values('Jamtara', (select stateid from States where RegionName='Jharkhand'))				
				
				
				
Insert into Districts(DistrictName,StateId) values('Bastar', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Bilaspur', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Dantewada', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Dhamtari', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Durg', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Janjgir-Champa', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Jashpur', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Kanker', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Kawardha', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Korba', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Koriya', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Mahasamund', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Raigarh', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Rajnandgaon', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Surguja', (select stateid from States where RegionName='Chhattisgarh'))				
Insert into Districts(DistrictName,StateId) values('Raipur', (select stateid from States where RegionName='Chhattisgarh'))				

go

insert into CityVillages (Name, DistrictId, CityOrVillage,CreatedBy,ModifiedBy)
select DistrictName , districtid, 'City' ,1,1 from Districts

go
