-- =============================================
-- Script Template
-- =============================================

/*Script to add dummy data into Users table*/
INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('RupaliSane'
		   ,'Ms'
           ,'RupaliSane'
           ,'Rsane@gmail.com'
           ,9888888888
           ,'QWNrU3VwQDEyMw=='
           ,'NirmalaJadhav'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('SanikaKulkarni'
		   ,'Ms'
           ,'Sanika'
           ,'Sanika@gmail.com'
           ,9777777777
           ,'QWNrU3VwQDEyMw=='
           ,'NishaSane'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('RakeshJadhav'
		   ,'Mr'
           ,'Rakesh'
           ,'Rakesh@gmail.com'
           ,9666666666
           ,'QWNrU3VwQDEyMw=='
           ,'MeenaMohite'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('ManojPatil'
		   ,'Mr'
           ,'Manoj'
           ,'ManojJ@gmail.com'
           ,9555555555
           ,'QWNrU3VwQDEyMw=='
           ,'AshaSawant'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('VijayMarne'
		   ,'Mr'
           ,'Vijay'
           ,'Vijay@gmail.com'
           ,9211111111
           ,'QWNrU3VwQDEyMw=='
           ,'SushamaDeshmukh'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('OmPrakashMehra'
		   ,'Mr'
           ,'Om'
           ,'Om@gmail.com'
           ,9333333333
           ,'QWNrU3VwQDEyMw=='
           ,'PoojaMehta'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('RevatiMore'
		   ,'Ms'
           ,'RevatiMane'
           ,'Revati@gmail.com'
           ,9511111111
           ,'QWNrU3VwQDEyMw=='
           ,'nalini'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('AsmaMukherjee'
		   ,'Ms'
           ,'Asma'
           ,'Asma@gmail.com'
           ,8777777777
           ,'QWNrU3VwQDEyMw=='
           ,'KrishnaSmarth'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('OmkarMohite'
		   ,'Mr'
           ,'Omkar'
           ,'Omkar@gmail.com'
           ,1111111111
           ,'QWNrU3VwQDEyMw=='
           ,'UshaMane'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('RajaPansare'
		   ,'Mr'
           ,'Raja'
           ,'Raja@gmail.com'
           ,8999999999
           ,'QWNrU3VwQDEyMw=='
           ,'RadhaPatil'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('PoonamMane'
		   ,'Ms'
           ,'Poonam'
           ,'Poonam@gmail.com'
           ,9911111111
           ,'QWNrU3VwQDEyMw=='
           ,'ArchanaMoghe'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('RajuChaudhary'
		   ,'Mr'
           ,'Raju'
           ,'Raju@gmail.com'
           ,9977777777
           ,'QWNrU3VwQDEyMw=='
           ,'MangalKanitkar'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('PrathamPant'
		   ,'Mr'
           ,'Pratham'
           ,'Pratham@gmail.com'
           ,9966666666
           ,'QWNrU3VwQDEyMw=='
           ,'RemaShinde'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('SupriyaMoghe'
		   ,'Ms'
           ,'Supriya'
           ,'Supriya@gmail.com'
           ,8887777777
           ,'QWNrU3VwQDEyMw=='
           ,'LatikaKulkarni'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('UdayKarmarkar'
		   ,'Mr'
           ,'Uday'
           ,'Uday@gmail.com'
           ,2222222222
           ,'QWNrU3VwQDEyMw=='
           ,'UrmilaDeshpande'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('MaheshGokhale'
		   ,'Mr'
           ,'Mahesh'
           ,'Mahesh@gmail.com'
           ,9876543219
           ,'QWNrU3VwQDEyMw=='
           ,'NishaGore'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('SanjayGupta'
		   ,'Mr'
           ,'Sanjay'
           ,'Sanjay@gmail.com'
           ,8765432198
           ,'QWNrU3VwQDEyMw=='
           ,'MadhuriGupte'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('SagarGhatge'
		   ,'Mr'
           ,'Sagar'
           ,'Sagar@gmail.com'
           ,8765432198
           ,'QWNrU3VwQDEyMw=='
           ,'ManishaShah'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('JaikishanLakhani'
		   ,'Mr'
           ,'Jay'
           ,'Jay@gmail.com'
           ,7654321989
           ,'QWNrU3VwQDEyMw=='
           ,'SwatiBhosale'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('AtulKulkarni'
		   ,'Mr'
           ,'Atul'
           ,'Atul@gmail.com'
           ,5432198964
           ,'QWNrU3VwQDEyMw=='
           ,'AnandiSohani'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('PratikPatil'
		   ,'Mr'
           ,'Pratik'
           ,'Pratik@gmail.com'
           ,4321989111
           ,'QWNrU3VwQDEyMw=='
           ,'PornimaMone'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('PrasadPatil'
		   ,'Mr'
           ,'Prasad'
           ,'Prasad@gmail.com'
           ,3219894444
           ,'QWNrU3VwQDEyMw=='
           ,'SeemaShinde'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('PritamBhosale'
		   ,'Ms'
           ,'Pritam'
           ,'Pritam@gmail.com'
           ,9411111111
           ,'QWNrU3VwQDEyMw=='
           ,'PriyaSarmane'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('SampadaShinde'
		   ,'Ms'
           ,'SampadaPatil'
           ,'Sampada@gmail.com'
           ,3222222222
           ,'QWNrU3VwQDEyMw=='
           ,'kavita'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('KavitaKrishnamurthy'
		   ,'Ms'
           ,'Kavita'
           ,'Kavita@gmail.com'
           ,9755555555
           ,'QWNrU3VwQDEyMw=='
           ,'HetalAnand'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('NileemaPisal'
		   ,'Ms'
           ,'Nileema'
           ,'Nileema@gmail.com'
           ,9444455555
           ,'QWNrU3VwQDEyMw=='
           ,'TinaGupta'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('AmrutaShinde'
		   ,'Ms'
           ,'Amruta'
           ,'Amruta@gmail.com'
           ,8944441111
           ,'QWNrU3VwQDEyMw=='
           ,'MalaMujumdar'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('MohanKulkarni'
		   ,'Mr'
           ,'Mohan'
           ,'Mohan@gmail.com'
           ,9677777777
           ,'QWNrU3VwQDEyMw=='
           ,'DishaKotnis'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('SadhanaSargam'
		   ,'Ms'
           ,'Sadhana'
           ,'Sadhana@gmail.com'
           ,8888888888
           ,'QWNrU3VwQDEyMw=='
           ,'LalitaMarane'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('LatikaPatil'
		   ,'Ms'
           ,'Latika'
           ,'Latika@gmail.com'
           ,6666666666
           ,'QWNrU3VwQDEyMw=='
           ,'TaraSharma'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('TanujaBhise'
		   ,'Ms'
           ,'TanujaKale'
           ,'Tanuja@gmail.com'
           ,5555555555
           ,'QWNrU3VwQDEyMw=='
           ,'namrata'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('AsmitaMore'
		   ,'Ms'
           ,'Asmita'
           ,'Asmita@gmail.com'
           ,3333333333
           ,'QWNrU3VwQDEyMw=='
           ,'AmrutaSubhash'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('NileshMoghe'
		   ,'Mr'
           ,'Nilesh'
           ,'Nilesh@gmail.com'
           ,1278872145
           ,'QWNrU3VwQDEyMw=='
           ,'RohiniGugar'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('AmolGupte'
		   ,'Mr'
           ,'Amol'
           ,'Amol@gmail.com'
           ,8527417894
           ,'QWNrU3VwQDEyMw=='
           ,'JayaPatil'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('SuvarnaSarmane'
		   ,'Ms'
           ,'Suvarna'
           ,'Suvarna@gmail.com'
           ,9638527410
           ,'QWNrU3VwQDEyMw=='
           ,'SavitaSawant'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('MonikaBajaj'
		   ,'Ms'
           ,'Monika'
           ,'Monika@gmail.com'
           ,7894561230
           ,'QWNrU3VwQDEyMw=='
           ,'MonaAgarwal'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('NishantKulkarni'
		   ,'Mr'
           ,'Nishant'
           ,'Nishant@gmail.com'
           ,3219894444
           ,'QWNrU3VwQDEyMw=='
           ,'RadhaKanitkar'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('RohiniKale'
		   ,'Ms'
           ,'Rohini'
           ,'Rohini@gmail.com'
           ,4561237891
           ,'QWNrU3VwQDEyMw=='
           ,'PayalPandit'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('RohanMujumdar'
		   ,'Mr'
           ,'Rohan'
           ,'Rohan@gmail.com'
           ,1234567890
           ,'QWNrU3VwQDEyMw=='
           ,'RoshaniSharma'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

INSERT INTO [CAMS].[dbo].[Users]
           ([Username]
		   ,[Title]
           ,[Name]
           ,[Email]
           ,[MobileNo]
           ,[Password]
           ,[MothersMaidenName]
           ,[CAId]
           ,[CountryCode]
           ,[CreatedBy]
           ,[CreatedDate]
           ,[DateOfBirth]
           ,[FailedPasswordAttemptCount]
           ,[FailedPasswordAttemptWindowStart]
           ,[IsActive]
           ,[IsLockedOut]
           ,[IsOnLine]
           ,[LastActivityDate]
           ,[LastLockedOutDate]
           ,[LastLoginDate]
           ,[LastPasswordChangedDate]
           ,[ModifiedBy]
           ,[ModifiedDate]
           ,[LastPassword]
           ,[SecondLastPassword]
           ,[SecondLastPasswordChangedDate]
           ,[IsDeleted]
           ,[AllowEdit]
           ,[AllowDelete]
           ,[DesignationId]
           ,[UserProfileId])
     VALUES
           ('RamavatiDeshmukh'
		   ,'Ms'
           ,'Rama'
           ,'Rama@gmail.com'
           ,2222222222
           ,'QWNrU3VwQDEyMw=='
           ,'MangalJadhav'
           ,null
           ,+91
           ,-1
           ,GETDATE()
           ,'10-10-1985'
           ,0
           ,GETDATE()
           ,1
           ,0
           ,0
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,GETDATE()
           ,1
           ,GETDATE()
           ,'QWNrU3VwQDEyMw=='
           ,'QWNrU3VwQDEyMw=='
           ,GETDATE()
           ,0
           ,0
           ,0
           ,null
           ,null)
GO

/*Script to assign usergroup to user*/
INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 2))
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 3))
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 4),(SELECT Users.UserId FROM Users WHERE Userid = 4)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 5)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 6)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 4),(SELECT Users.UserId FROM Users WHERE Userid = 7)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 8)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 9)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 10)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 11)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 12))
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 13))
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 4),(SELECT Users.UserId FROM Users WHERE Userid = 14)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 15)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 16)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 4),(SELECT Users.UserId FROM Users WHERE Userid = 17)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 18)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 19)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 20)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 21)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 22))
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 23))
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 4),(SELECT Users.UserId FROM Users WHERE Userid = 24)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 25)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 26)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 4),(SELECT Users.UserId FROM Users WHERE Userid = 27)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 28)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 29)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 30)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 31)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 32))
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 33))
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 4),(SELECT Users.UserId FROM Users WHERE Userid = 34)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 35)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 36)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 4),(SELECT Users.UserId FROM Users WHERE Userid = 37)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 2),(SELECT Users.UserId FROM Users WHERE Userid = 38)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 39)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 40)) 
GO

INSERT INTO [CAMS].[dbo].[UserUserGroups]([UserGroupid],[Userid]) VALUES ((SELECT UserGroups.UserGroupId FROM UserGroups WHERE UserGroupid = 3),(SELECT Users.UserId FROM Users WHERE Userid = 41)) 
GO