//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cams.Web.MVCRazor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorAndValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorAndValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cams.Web.MVCRazor.ErrorAndValidationMessages", typeof(ErrorAndValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias name of bank is required..
        /// </summary>
        public static string ABMtxtppAlias {
            get {
                return ResourceManager.GetString("ABMtxtppAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name is required..
        /// </summary>
        public static string ABMtxtppBankName {
            get {
                return ResourceManager.GetString("ABMtxtppBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank website URL is required..
        /// </summary>
        public static string ABMtxtppURL {
            get {
                return ResourceManager.GetString("ABMtxtppURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.  Enter proper website address..
        /// </summary>
        public static string ABMtxtppURLRegEx {
            get {
                return ResourceManager.GetString("ABMtxtppURLRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required no. of partners already added. To add more partners, please update no. of partners..
        /// </summary>
        public static string AddClientPartnerError {
            get {
                return ResourceManager.GetString("AddClientPartnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity already exists..
        /// </summary>
        public static string AddCommodityAddError {
            get {
                return ResourceManager.GetString("AddCommodityAddError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity Image is required..
        /// </summary>
        public static string AddCommodityImageRequired {
            get {
                return ResourceManager.GetString("AddCommodityImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour charge already exists..
        /// </summary>
        public static string AddLCTFailed {
            get {
                return ResourceManager.GetString("AddLCTFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Unit and it&apos;s Equivalent unit value are required..
        /// </summary>
        public static string AddMUDataRequired {
            get {
                return ResourceManager.GetString("AddMUDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add {0} to {1}.  Zone already exist..
        /// </summary>
        public static string AddZoneAddZoneFailed {
            get {
                return ResourceManager.GetString("AddZoneAddZoneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email1: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string AOErrorRegExEmail1 {
            get {
                return ResourceManager.GetString("AOErrorRegExEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Invalid Email2: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string AOErrorRegExEmail2 {
            get {
                return ResourceManager.GetString("AOErrorRegExEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PAN.  Only alphabets and numbers are allowed. Length should be 10 characters long..
        /// </summary>
        public static string AOErrorRegExPAN {
            get {
                return ResourceManager.GetString("AOErrorRegExPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Name: Only alphabets and numbers are allowed..
        /// </summary>
        public static string AOErrorRegExPartnerName {
            get {
                return ResourceManager.GetString("AOErrorRegExPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UID: Should be numeric and atleast 12 digit long..
        /// </summary>
        public static string AOErrorRegExUID {
            get {
                return ResourceManager.GetString("AOErrorRegExUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is required.
        /// </summary>
        public static string AOErrorRequiredDOB {
            get {
                return ResourceManager.GetString("AOErrorRequiredDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email1 is required..
        /// </summary>
        public static string AOErrorRequiredEmail1 {
            get {
                return ResourceManager.GetString("AOErrorRequiredEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN is required.
        /// </summary>
        public static string AOErrorRequiredPAN {
            get {
                return ResourceManager.GetString("AOErrorRequiredPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string AOErrorRequiredPartnerName {
            get {
                return ResourceManager.GetString("AOErrorRequiredPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Invalid Email1: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string AOGardianErrorRegExEmail1 {
            get {
                return ResourceManager.GetString("AOGardianErrorRegExEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Invalid Email2: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string AOGardianErrorRegExEmail2 {
            get {
                return ResourceManager.GetString("AOGardianErrorRegExEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Guardian Name: Only alphabets and numbers are allowed..
        /// </summary>
        public static string AOGardianErrorRegExGardianName {
            get {
                return ResourceManager.GetString("AOGardianErrorRegExGardianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PAN.  Only alphabets and numbers are allowed. Length should be 10 characters long..
        /// </summary>
        public static string AOGardianErrorRegExPAN {
            get {
                return ResourceManager.GetString("AOGardianErrorRegExPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UID: Should be numeric and atleast 12 digit long..
        /// </summary>
        public static string AOGardianErrorRegExUID {
            get {
                return ResourceManager.GetString("AOGardianErrorRegExUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: City/Village is required..
        /// </summary>
        public static string AOGPIReqCity {
            get {
                return ResourceManager.GetString("AOGPIReqCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardian Details: Invalid Email1: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string AOGRegExEmail1 {
            get {
                return ResourceManager.GetString("AOGRegExEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardian Details: Invalid Email2: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string AOGRegExEmail2 {
            get {
                return ResourceManager.GetString("AOGRegExEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Invalid PAN: Should be 10 characters long..
        /// </summary>
        public static string AOGRegExPAN {
            get {
                return ResourceManager.GetString("AOGRegExPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Invalid PIN: Should be numeric and atleast 6 digit long..
        /// </summary>
        public static string AOGRegExPIN {
            get {
                return ResourceManager.GetString("AOGRegExPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Invalid UID: Should be numeric and atleast 12 digit long..
        /// </summary>
        public static string AOGRegExUID {
            get {
                return ResourceManager.GetString("AOGRegExUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Address is required..
        /// </summary>
        public static string AOGReqAddr1 {
            get {
                return ResourceManager.GetString("AOGReqAddr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Email1 is required..
        /// </summary>
        public static string AOGReqEmail1 {
            get {
                return ResourceManager.GetString("AOGReqEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Atleast one Mobile number is required..
        /// </summary>
        public static string AOGReqMobNo {
            get {
                return ResourceManager.GetString("AOGReqMobNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardian Details: PAN is required..
        /// </summary>
        public static string AOGReqPAN {
            get {
                return ResourceManager.GetString("AOGReqPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gardian Details: PIN is required..
        /// </summary>
        public static string AOGReqPIN {
            get {
                return ResourceManager.GetString("AOGReqPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Farewell date.
        /// </summary>
        public static string AOPIFarewellDateError {
            get {
                return ResourceManager.GetString("AOPIFarewellDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number(s) should be numeric and atleast 6 digit long..
        /// </summary>
        public static string AOPIRegExContactNo {
            get {
                return ResourceManager.GetString("AOPIRegExContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date of Birth.
        /// </summary>
        public static string AOPIRegXExDOB {
            get {
                return ResourceManager.GetString("AOPIRegXExDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City/Village is required..
        /// </summary>
        public static string AOPIReqCity {
            get {
                return ResourceManager.GetString("AOPIReqCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation is required.
        /// </summary>
        public static string AOPIReqDesignation {
            get {
                return ResourceManager.GetString("AOPIReqDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is required.
        /// </summary>
        public static string AOPIReqExDOB {
            get {
                return ResourceManager.GetString("AOPIReqExDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast one Mobile number is required..
        /// </summary>
        public static string AOPIReqMobNo {
            get {
                return ResourceManager.GetString("AOPIReqMobNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN: Should be numeric and atleast 6 digit long..
        /// </summary>
        public static string AORegExPIN {
            get {
                return ResourceManager.GetString("AORegExPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid UID: Should be numeric and atleast 12 digit long..
        /// </summary>
        public static string AORegExUID {
            get {
                return ResourceManager.GetString("AORegExUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required..
        /// </summary>
        public static string AOReqAddr1 {
            get {
                return ResourceManager.GetString("AOReqAddr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is required..
        /// </summary>
        public static string AOReqPIN {
            get {
                return ResourceManager.GetString("AOReqPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the State, District and City for APMC.
        /// </summary>
        public static string APMCCityRequired {
            get {
                return ResourceManager.GetString("APMCCityRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APMC already exists..
        /// </summary>
        public static string APMCExists {
            get {
                return ResourceManager.GetString("APMCExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APMC address is required..
        /// </summary>
        public static string APMCValidateAddress {
            get {
                return ResourceManager.GetString("APMCValidateAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APMC name is required..
        /// </summary>
        public static string APMCValidateNAME {
            get {
                return ResourceManager.GetString("APMCValidateNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Branch name.  Only alphabets and numbers are allowed. Length should not exceed 60 characters..
        /// </summary>
        public static string BBErrorRegExBranchName {
            get {
                return ResourceManager.GetString("BBErrorRegExBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number(s) should be numeric and atleast 5 digit long..
        /// </summary>
        public static string BBErrorRegExContactNo {
            get {
                return ResourceManager.GetString("BBErrorRegExContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email1: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string BBErrorRegExEmail1 {
            get {
                return ResourceManager.GetString("BBErrorRegExEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email2: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string BBErrorRegExEmail2 {
            get {
                return ResourceManager.GetString("BBErrorRegExEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IFSC Code.  Only alphabets and numbers are allowed. Length should be 11 characters long..
        /// </summary>
        public static string BBErrorRegExIFSC {
            get {
                return ResourceManager.GetString("BBErrorRegExIFSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MICR Code.  Only numbers are allowed.  Length should be 9 digit long..
        /// </summary>
        public static string BBErrorRegExMICR {
            get {
                return ResourceManager.GetString("BBErrorRegExMICR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN. Only numbers are allowed.  Length should be 6 digits long..
        /// </summary>
        public static string BBErrorRegExPIN {
            get {
                return ResourceManager.GetString("BBErrorRegExPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STD code should be numeric and atleast 3 digit long..
        /// </summary>
        public static string BBErrorRegExSTDCode {
            get {
                return ResourceManager.GetString("BBErrorRegExSTDCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SWIFT Code.  Only alphabets and numbers are allowed. Length should not exceed 15 characters..
        /// </summary>
        public static string BBErrorRegExSWIFT {
            get {
                return ResourceManager.GetString("BBErrorRegExSWIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required..
        /// </summary>
        public static string BBErrorRequiredAddressLine1 {
            get {
                return ResourceManager.GetString("BBErrorRequiredAddressLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank is required..
        /// </summary>
        public static string BBErrorRequiredBank {
            get {
                return ResourceManager.GetString("BBErrorRequiredBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City / Village is required..
        /// </summary>
        public static string BBErrorRequiredCityVillage {
            get {
                return ResourceManager.GetString("BBErrorRequiredCityVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is required..
        /// </summary>
        public static string BBErrorRequiredPIN {
            get {
                return ResourceManager.GetString("BBErrorRequiredPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create {0} branch of {1} bank..
        /// </summary>
        public static string BBRAddFailed {
            get {
                return ResourceManager.GetString("BBRAddFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required..
        /// </summary>
        public static string BBReqAddress {
            get {
                return ResourceManager.GetString("BBReqAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name required..
        /// </summary>
        public static string BBRequiredBranchName {
            get {
                return ResourceManager.GetString("BBRequiredBranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email1 is required..
        /// </summary>
        public static string BBRequiredEmail1 {
            get {
                return ResourceManager.GetString("BBRequiredEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFSC Code required..
        /// </summary>
        public static string BBRequiredIFSC {
            get {
                return ResourceManager.GetString("BBRequiredIFSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICR Code required..
        /// </summary>
        public static string BBRequiredMICR {
            get {
                return ResourceManager.GetString("BBRequiredMICR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT Code required..
        /// </summary>
        public static string BBRequiredSWIFT {
            get {
                return ResourceManager.GetString("BBRequiredSWIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank &amp; branch already registered..
        /// </summary>
        public static string BRBankBranchNameValidation {
            get {
                return ResourceManager.GetString("BRBankBranchNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank already exists..
        /// </summary>
        public static string BRBankNameValidation {
            get {
                return ResourceManager.GetString("BRBankNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botanical name already used for commodity {0}..
        /// </summary>
        public static string BRBotanicalNameValidation {
            get {
                return ResourceManager.GetString("BRBotanicalNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place already exists..
        /// </summary>
        public static string BRCityVillageNameValidation {
            get {
                return ResourceManager.GetString("BRCityVillageNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APMC license no. already exists for {0} {1}.
        /// </summary>
        public static string BRClientAPMCLicNoUnique {
            get {
                return ResourceManager.GetString("BRClientAPMCLicNoUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required..
        /// </summary>
        public static string BRClientMissingCityVillage {
            get {
                return ResourceManager.GetString("BRClientMissingCityVillage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN number already exists for client {0} {1}.
        /// </summary>
        public static string BRClientPANUnique {
            get {
                return ResourceManager.GetString("BRClientPANUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAN number already exists for client {0} {1}.
        /// </summary>
        public static string BRClientTANUnique {
            get {
                return ResourceManager.GetString("BRClientTANUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client already registered..
        /// </summary>
        public static string BRClientUnique {
            get {
                return ResourceManager.GetString("BRClientUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity already exists..
        /// </summary>
        public static string BRCommodityNameValidation {
            get {
                return ResourceManager.GetString("BRCommodityNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country not found..
        /// </summary>
        public static string BRCountryValidation {
            get {
                return ResourceManager.GetString("BRCountryValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is required..
        /// </summary>
        public static string BRDateOfBirth {
            get {
                return ResourceManager.GetString("BRDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation is required..
        /// </summary>
        public static string BRDesignationName {
            get {
                return ResourceManager.GetString("BRDesignationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation already exist..
        /// </summary>
        public static string BRDesignationUnique {
            get {
                return ResourceManager.GetString("BRDesignationUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District already exists..
        /// </summary>
        public static string BRDistrictNameValidation {
            get {
                return ResourceManager.GetString("BRDistrictNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is required..
        /// </summary>
        public static string BREmail {
            get {
                return ResourceManager.GetString("BREmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IFSC code already used for bank {0} and branch {1}..
        /// </summary>
        public static string BRIFSCCode {
            get {
                return ResourceManager.GetString("BRIFSCCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create new labour charges..
        /// </summary>
        public static string BRLabourChargeAllowedValidation {
            get {
                return ResourceManager.GetString("BRLabourChargeAllowedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour charge already exist..
        /// </summary>
        public static string BRLabourChargeValidation {
            get {
                return ResourceManager.GetString("BRLabourChargeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MICR code already used for bank {0} and branch {1}..
        /// </summary>
        public static string BRMICRCode {
            get {
                return ResourceManager.GetString("BRMICRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is required..
        /// </summary>
        public static string BRMobileNo {
            get {
                return ResourceManager.GetString("BRMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s maiden name is required..
        /// </summary>
        public static string BRMothersMaidenName {
            get {
                return ResourceManager.GetString("BRMothersMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Unit already exist..
        /// </summary>
        public static string BRMUMeasuringUnitValidation {
            get {
                return ResourceManager.GetString("BRMUMeasuringUnitValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required..
        /// </summary>
        public static string BRName {
            get {
                return ResourceManager.GetString("BRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string BRPassword {
            get {
                return ResourceManager.GetString("BRPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship is required..
        /// </summary>
        public static string BRRelationshipName {
            get {
                return ResourceManager.GetString("BRRelationshipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship already exist..
        /// </summary>
        public static string BRRelationshipUnique {
            get {
                return ResourceManager.GetString("BRRelationshipUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Union Teritorry Saved..
        /// </summary>
        public static string BRStateSaved {
            get {
                return ResourceManager.GetString("BRStateSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State/Union Teritorry already exists..
        /// </summary>
        public static string BRStateValidation {
            get {
                return ResourceManager.GetString("BRStateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SWIFT code already used for bank {0} and branch {1}..
        /// </summary>
        public static string BRSWIFTCode {
            get {
                return ResourceManager.GetString("BRSWIFTCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group is required..
        /// </summary>
        public static string BRUserGroupNameDisplay {
            get {
                return ResourceManager.GetString("BRUserGroupNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group is required..
        /// </summary>
        public static string BRUserGroupNameRequired {
            get {
                return ResourceManager.GetString("BRUserGroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group already exist..
        /// </summary>
        public static string BRUserGroupNameUnique {
            get {
                return ResourceManager.GetString("BRUserGroupNameUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string BRUserName {
            get {
                return ResourceManager.GetString("BRUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone already exists..
        /// </summary>
        public static string BRZoneNameValidation {
            get {
                return ResourceManager.GetString("BRZoneNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APMC license already expired..
        /// </summary>
        public static string ClientErrorAPMCLicenseNoDate {
            get {
                return ResourceManager.GetString("ClientErrorAPMCLicenseNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 3 commodity classes can be selected at a time..
        /// </summary>
        public static string ClientErrorCommodityClass {
            get {
                return ResourceManager.GetString("ClientErrorCommodityClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number(s) should be numeric and atleast 6 digit long..
        /// </summary>
        public static string ClientErrorRegExContactNo {
            get {
                return ResourceManager.GetString("ClientErrorRegExContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Profile: Invalid Email1: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string ClientErrorRegExEmail1 {
            get {
                return ResourceManager.GetString("ClientErrorRegExEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Profile: Invalid Email2: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string ClientErrorRegExEmail2 {
            get {
                return ResourceManager.GetString("ClientErrorRegExEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN should be 10 characters long..
        /// </summary>
        public static string ClientErrorRegExPAN {
            get {
                return ResourceManager.GetString("ClientErrorRegExPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN. Only numbers are allowed.  Length should be 6 digits long..
        /// </summary>
        public static string ClientErrorRegExPIN {
            get {
                return ResourceManager.GetString("ClientErrorRegExPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STD code should be numeric and atleast 3 digit long..
        /// </summary>
        public static string ClientErrorRegExSTDCode {
            get {
                return ResourceManager.GetString("ClientErrorRegExSTDCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAN should be 10 characters long..
        /// </summary>
        public static string ClientErrorRegExTAN {
            get {
                return ResourceManager.GetString("ClientErrorRegExTAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account relationship manager is required..
        /// </summary>
        public static string ClientErrorRequiredAccountManagerId {
            get {
                return ResourceManager.GetString("ClientErrorRequiredAccountManagerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APMC license number is required..
        /// </summary>
        public static string ClientErrorRequiredAPMCLicenseNo {
            get {
                return ResourceManager.GetString("ClientErrorRequiredAPMCLicenseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APMC license validity date is required..
        /// </summary>
        public static string ClientErrorRequiredAPMCLicenseNoDate {
            get {
                return ResourceManager.GetString("ClientErrorRequiredAPMCLicenseNoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APMC is required..
        /// </summary>
        public static string ClientErrorRequiredAPMCName {
            get {
                return ResourceManager.GetString("ClientErrorRequiredAPMCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity Class is required..
        /// </summary>
        public static string ClientErrorRequiredCommodityClass {
            get {
                return ResourceManager.GetString("ClientErrorRequiredCommodityClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email1 is required..
        /// </summary>
        public static string ClientErrorRequiredEmail1 {
            get {
                return ResourceManager.GetString("ClientErrorRequiredEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN is required..
        /// </summary>
        public static string ClientErrorRequiredPAN {
            get {
                return ResourceManager.GetString("ClientErrorRequiredPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is required..
        /// </summary>
        public static string ClientErrorRequiredPIN {
            get {
                return ResourceManager.GetString("ClientErrorRequiredPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary contact person mobile no. already exist..
        /// </summary>
        public static string ClientPrimaryContactErrorMobileNo {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number(s) should be numeric and atleast 6 digit long..
        /// </summary>
        public static string ClientPrimaryContactErrorRegExContactNo {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRegExContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact Person: Invalid Email1: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string ClientPrimaryContactErrorRegExEmail1 {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRegExEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact Person: Invalid Email2: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string ClientPrimaryContactErrorRegExEmail2 {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRegExEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact Person: PAN should be 10 characters long..
        /// </summary>
        public static string ClientPrimaryContactErrorRegExPAN {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRegExPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN. Only numbers are allowed.  Length should be 6 digits long..
        /// </summary>
        public static string ClientPrimaryContactErrorRegExPIN {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRegExPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STD code should be numeric and atleast 3 digit long..
        /// </summary>
        public static string ClientPrimaryContactErrorRegExSTDCode {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRegExSTDCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact Person: Invalid UID: Should be numeric and atleast 12 digit long..
        /// </summary>
        public static string ClientPrimaryContactErrorRegExUID {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRegExUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Contact Person: Date of birth is required..
        /// </summary>
        public static string ClientPrimaryContactErrorRequiredDOB {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRequiredDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number is required..
        /// </summary>
        public static string ClientPrimaryContactErrorRequiredMobileNo {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRequiredMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN is required..
        /// </summary>
        public static string ClientPrimaryContactErrorRequiredPAN {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRequiredPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is required..
        /// </summary>
        public static string ClientPrimaryContactErrorRequiredPIN {
            get {
                return ResourceManager.GetString("ClientPrimaryContactErrorRequiredPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s maiden name is required..
        /// </summary>
        public static string ClientPrimaryContactMothersMaidenName {
            get {
                return ResourceManager.GetString("ClientPrimaryContactMothersMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary contact person designationis requied..
        /// </summary>
        public static string ClientPrimaryContactRequiredDesignationName {
            get {
                return ResourceManager.GetString("ClientPrimaryContactRequiredDesignationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary contact person name is requied..
        /// </summary>
        public static string ClientPrimaryContactRequiredName {
            get {
                return ResourceManager.GetString("ClientPrimaryContactRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        public static string CLRACPRequiredName {
            get {
                return ResourceManager.GetString("CLRACPRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias name required..
        /// </summary>
        public static string CLRCompanyAliasNameRequired {
            get {
                return ResourceManager.GetString("CLRCompanyAliasNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email1: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string CLRCompanyEmailRegEx {
            get {
                return ResourceManager.GetString("CLRCompanyEmailRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email1 is required..
        /// </summary>
        public static string CLRCompanyEmailRequired {
            get {
                return ResourceManager.GetString("CLRCompanyEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Company name.Only alphabets and numbers are allowed..
        /// </summary>
        public static string CLRCompanyNameRegEx {
            get {
                return ResourceManager.GetString("CLRCompanyNameRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name is required..
        /// </summary>
        public static string CLRCompanyNameRequired {
            get {
                return ResourceManager.GetString("CLRCompanyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN is required..
        /// </summary>
        public static string CLRCompanyPANRequired {
            get {
                return ResourceManager.GetString("CLRCompanyPANRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAN is required.
        /// </summary>
        public static string CLRCompanyTANRequired {
            get {
                return ResourceManager.GetString("CLRCompanyTANRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity Class is required.
        /// </summary>
        public static string CommmodityRequiredCommodityClassId {
            get {
                return ResourceManager.GetString("CommmodityRequiredCommodityClassId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botnical Name: Only alphabets and numbers are allowed. Length should not exceed 20 characters..
        /// </summary>
        public static string CommodityRegXBotnicalName {
            get {
                return ResourceManager.GetString("CommodityRegXBotnicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity: Only alphabets and numbers are allowed. Length should not be exceed 20 characters..
        /// </summary>
        public static string CommodityRegXName {
            get {
                return ResourceManager.GetString("CommodityRegXName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Botnical Name is required..
        /// </summary>
        public static string CommodityRequiredBotnicalName {
            get {
                return ResourceManager.GetString("CommodityRequiredBotnicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodity is required..
        /// </summary>
        public static string CommodityRequiredName {
            get {
                return ResourceManager.GetString("CommodityRequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string ERLogin {
            get {
                return ResourceManager.GetString("ERLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occurred. Go to.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atleast two partners should have age above 18.
        /// </summary>
        public static string ErrorMinorClientPartner {
            get {
                return ResourceManager.GetString("ErrorMinorClientPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Date of Birth: Age should be above 18.
        /// </summary>
        public static string ErrorMinorSPClientPartner {
            get {
                return ResourceManager.GetString("ErrorMinorSPClientPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Invalid Guardian Name: Only alphabets and numbers are allowed..
        /// </summary>
        public static string GardianReqgExName {
            get {
                return ResourceManager.GetString("GardianReqgExName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardian Details: Guardian name is required.
        /// </summary>
        public static string GardianReqName {
            get {
                return ResourceManager.GetString("GardianReqName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Labour Charge: Only alphabets and numbers are allowed. Length should not be exceed 30 characters..
        /// </summary>
        public static string LCTErrorRegExLabourCharge {
            get {
                return ResourceManager.GetString("LCTErrorRegExLabourCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labour charge required..
        /// </summary>
        public static string LCTRequiredLabourCharge {
            get {
                return ResourceManager.GetString("LCTRequiredLabourCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save..
        /// </summary>
        public static string MUFailed {
            get {
                return ResourceManager.GetString("MUFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Measurement Unit: Only decimal numbers are allowed..
        /// </summary>
        public static string MURegExEquivalentUnit {
            get {
                return ResourceManager.GetString("MURegExEquivalentUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Equivalent Unit:  Only alphabets and numbers are allowed. Length should not exceed 20 characters..
        /// </summary>
        public static string MURegExMeasurementUnit {
            get {
                return ResourceManager.GetString("MURegExMeasurementUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password should contain 6 – 12 characters and should include Uppercase/Lowercase letters, Numerals and Symbols.Space is not allowed..
        /// </summary>
        public static string RegExpForNewPassword {
            get {
                return ResourceManager.GetString("RegExpForNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Groupname. Only alphabets and numbers are allowed. Length should not exceed 30 characters..
        /// </summary>
        public static string UGErrorRegExGroupname {
            get {
                return ResourceManager.GetString("UGErrorRegExGroupname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description should not be greater than 150 characters..
        /// </summary>
        public static string UGValidateDescription {
            get {
                return ResourceManager.GetString("UGValidateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age is less than 18 years..
        /// </summary>
        public static string URAgeCheckMsg {
            get {
                return ResourceManager.GetString("URAgeCheckMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID: should be 4 digit number..
        /// </summary>
        public static string URErrorRegExClientID {
            get {
                return ResourceManager.GetString("URErrorRegExClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth: Date should be in format DD-MM-YYYY..
        /// </summary>
        public static string URErrorRegExDOB {
            get {
                return ResourceManager.GetString("URErrorRegExDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string URErrorRegExEmail {
            get {
                return ResourceManager.GetString("URErrorRegExEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name: Only alphabets and numbers are allowed..
        /// </summary>
        public static string URErrorRegExFullName {
            get {
                return ResourceManager.GetString("URErrorRegExFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No. should be 10-15 digit long..
        /// </summary>
        public static string URErrorRegExMobileNumber {
            get {
                return ResourceManager.GetString("URErrorRegExMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Maiden Name: Alphabets and numbers are allowed. Length should not exceed 15 characters..
        /// </summary>
        public static string URErrorRegExMothersMaidenName {
            get {
                return ResourceManager.GetString("URErrorRegExMothersMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username. Only alphabets and numbers are allowed. Length should be 8-15 characters long..
        /// </summary>
        public static string URErrorRegExUsername {
            get {
                return ResourceManager.GetString("URErrorRegExUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Name/ID is required..
        /// </summary>
        public static string URErrorRequiredClientID {
            get {
                return ResourceManager.GetString("URErrorRequiredClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is required..
        /// </summary>
        public static string URErrorRequiredDOB {
            get {
                return ResourceManager.GetString("URErrorRequiredDOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string URErrorRequiredEmail {
            get {
                return ResourceManager.GetString("URErrorRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name is required..
        /// </summary>
        public static string URErrorRequiredFullName {
            get {
                return ResourceManager.GetString("URErrorRequiredFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number is required..
        /// </summary>
        public static string URErrorRequiredMobileNumber {
            get {
                return ResourceManager.GetString("URErrorRequiredMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother&apos;s Maiden Name is required..
        /// </summary>
        public static string URErrorRequiredMothersMaidenName {
            get {
                return ResourceManager.GetString("URErrorRequiredMothersMaidenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string URErrorRequiredUsername {
            get {
                return ResourceManager.GetString("URErrorRequiredUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information: Contact Number(s) should be numeric and atleast 6 digit long..
        /// </summary>
        public static string URPIRegExContactNo {
            get {
                return ResourceManager.GetString("URPIRegExContactNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information: Invalid Email1: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string URPIRegExEmail1 {
            get {
                return ResourceManager.GetString("URPIRegExEmail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information: Invalid Email2: Enter proper email address(eg: example@abc.com)..
        /// </summary>
        public static string URPIRegExEmail2 {
            get {
                return ResourceManager.GetString("URPIRegExEmail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN should be 10 characters long..
        /// </summary>
        public static string URRegExPAN {
            get {
                return ResourceManager.GetString("URRegExPAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN: Should be numeric and atleast 6 digit long..
        /// </summary>
        public static string URRegExPIN {
            get {
                return ResourceManager.GetString("URRegExPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information: Invalid UID: Should be numeric and atleast 12 digit long..
        /// </summary>
        public static string URRegExUID {
            get {
                return ResourceManager.GetString("URRegExUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registration failed.  Please correct the following fields:.
        /// </summary>
        public static string URRegistrationFailed {
            get {
                return ResourceManager.GetString("URRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User registered successfully..
        /// </summary>
        public static string URRegistrationSuccessful {
            get {
                return ResourceManager.GetString("URRegistrationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation is required..
        /// </summary>
        public static string URReqDesignation {
            get {
                return ResourceManager.GetString("URReqDesignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User should belong to atleast one user group..
        /// </summary>
        public static string URReqUserGroup {
            get {
                return ResourceManager.GetString("URReqUserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not available.&lt;br /&gt;Some suggested Usernames: {1}{2}.
        /// </summary>
        public static string URSuggestedUsername {
            get {
                return ResourceManager.GetString("URSuggestedUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists..
        /// </summary>
        public static string URUserAlreadyExist {
            get {
                return ResourceManager.GetString("URUserAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password is required.
        /// </summary>
        public static string ValidateConfirmPassword {
            get {
                return ResourceManager.GetString("ValidateConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you gave is incorrect.
        /// </summary>
        public static string ValidateExistingPassword {
            get {
                return ResourceManager.GetString("ValidateExistingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password is required.
        /// </summary>
        public static string ValidateNewPassword {
            get {
                return ResourceManager.GetString("ValidateNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string ValidatePassword {
            get {
                return ResourceManager.GetString("ValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string ValidatePasswordMatch {
            get {
                return ResourceManager.GetString("ValidatePasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password should not be same as existing password.
        /// </summary>
        public static string ValidatePasswordWithExistingPassword {
            get {
                return ResourceManager.GetString("ValidatePasswordWithExistingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password should not be same as last two passwords.
        /// </summary>
        public static string ValidatePasswordWithLastTwoPasswords {
            get {
                return ResourceManager.GetString("ValidatePasswordWithLastTwoPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Zone. Only alphabets and numbers are allowed..
        /// </summary>
        public static string ZoneRegXZone {
            get {
                return ResourceManager.GetString("ZoneRegXZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone is required..
        /// </summary>
        public static string ZoneRequiredZone {
            get {
                return ResourceManager.GetString("ZoneRequiredZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone For is required..
        /// </summary>
        public static string ZoneRequiredZoneFor {
            get {
                return ResourceManager.GetString("ZoneRequiredZoneFor", resourceCulture);
            }
        }
    }
}
